# roles/mariadb/tasks/install.yml
---

- name: Add official MariaDB repository
  template:
    src: etc_yum.repos.d_mariadb.repo.j2
    dest: /etc/yum.repos.d/MariaDB.repo
  tags: mariadb

- name: Install packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ mariadb_packages }}"
  tags: mariadb
