dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
# Linting with yamllint and ansible-lint
# verify.yml is skipped because it uses the shell: module, which would trigger
# a linting error.
lint: |
  yamllint .
  ansible-lint --exclude=molecule/default/verify.yml
platforms:
  - name: dbc76
    box: bento/centos-7.6
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.76"
  - name: dbc80
    box: bento/centos-8
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: "192.168.56.80"
provisioner:
  name: ansible
verifier:
  name: ansible
